"""initial_baseline

Revision ID: 2299f7d46a8d
Revises: 
Create Date: 2025-11-05 22:53:28.979090

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2299f7d46a8d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assembly_has_chr',
    sa.Column('assembly_id', sa.Integer(), nullable=False, comment='Assembly ID'),
    sa.Column('chr_id', sa.Integer(), nullable=False, comment='Chromosome ID'),
    sa.PrimaryKeyConstraint('assembly_id', 'chr_id'),
    comment='Association table linking assemblies to chromosomes'
    )
    op.create_index('idx_assembly_has_chr_assembly', 'assembly_has_chr', ['assembly_id'], unique=False)
    op.create_index('idx_assembly_has_chr_chr', 'assembly_has_chr', ['chr_id'], unique=False)
    op.create_table('editor',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for editor'),
    sa.Column('display_name', sa.String(length=128), nullable=False, comment='Display name for editor'),
    sa.Column('first_name', sa.String(length=128), nullable=True, comment='First name'),
    sa.Column('last_name', sa.String(length=128), nullable=True, comment='Last name'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='Email address'),
    sa.Column('password', sa.String(length=255), nullable=True, comment='Password hash'),
    sa.Column('current', sa.Boolean(), nullable=False, comment='Whether this is the current editor'),
    sa.Column('connected', sa.Boolean(), nullable=False, comment='Connection status'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flag_class',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for flag class'),
    sa.Column('class_name', sa.String(length=255), nullable=False, comment='Flag class name'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gene_alt_name',
    sa.Column('id', sa.Integer(), nullable=False, comment='Association ID'),
    sa.Column('genefam_id', sa.Integer(), nullable=False, comment='Genefam ID'),
    sa.Column('name_id', sa.Integer(), nullable=False, comment='Alternative name ID'),
    sa.PrimaryKeyConstraint('id'),
    comment='Association table linking genefams to alternative names'
    )
    op.create_index('idx_gene_alt_name_genefam', 'gene_alt_name', ['genefam_id'], unique=False)
    op.create_index('idx_gene_alt_name_name_id', 'gene_alt_name', ['name_id'], unique=False)
    op.create_table('gene_alt_symbol',
    sa.Column('id', sa.Integer(), nullable=False, comment='Association ID'),
    sa.Column('genefam_id', sa.Integer(), nullable=False, comment='Genefam ID'),
    sa.Column('symbol_id', sa.Integer(), nullable=False, comment='Alternative symbol ID'),
    sa.PrimaryKeyConstraint('id'),
    comment='Association table linking genefams to alternative symbols'
    )
    op.create_index('idx_gene_alt_symbol_genefam', 'gene_alt_symbol', ['genefam_id'], unique=False)
    op.create_index('idx_gene_alt_symbol_symbol_id', 'gene_alt_symbol', ['symbol_id'], unique=False)
    op.create_table('gene_has_comment',
    sa.Column('genefam_id', sa.Integer(), nullable=False, comment='Genefam ID'),
    sa.Column('comment_id', sa.Integer(), nullable=False, comment='Comment ID'),
    sa.PrimaryKeyConstraint('genefam_id', 'comment_id'),
    comment='Association table linking genefams to comments'
    )
    op.create_index('idx_gene_has_comment_comment', 'gene_has_comment', ['comment_id'], unique=False)
    op.create_index('idx_gene_has_comment_genefam', 'gene_has_comment', ['genefam_id'], unique=False)
    op.create_table('gene_has_family',
    sa.Column('genefam_id', sa.Integer(), nullable=False, comment='Genefam ID'),
    sa.Column('family_id', sa.Integer(), nullable=False, comment='Family ID'),
    sa.Column('url', sa.String(length=255), nullable=True, comment='URL reference'),
    sa.Column('custom_sort', sa.String(length=255), nullable=True, comment='Custom sort order'),
    sa.PrimaryKeyConstraint('genefam_id', 'family_id'),
    comment='Association table linking genefams to families'
    )
    op.create_index('idx_gene_has_family_family', 'gene_has_family', ['family_id'], unique=False)
    op.create_index('idx_gene_has_family_genefam', 'gene_has_family', ['genefam_id'], unique=False)
    op.create_table('gene_has_flag',
    sa.Column('genefam_id', sa.Integer(), nullable=False, comment='Genefam ID'),
    sa.Column('flag_id', sa.Integer(), nullable=False, comment='Gene flag ID'),
    sa.PrimaryKeyConstraint('genefam_id', 'flag_id'),
    comment='Association table linking genefams to flags'
    )
    op.create_index('idx_gene_has_flag_flag', 'gene_has_flag', ['flag_id'], unique=False)
    op.create_index('idx_gene_has_flag_genefam', 'gene_has_flag', ['genefam_id'], unique=False)
    op.create_table('gene_status',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for gene status'),
    sa.Column('status', sa.String(length=45), nullable=False, comment='Status name'),
    sa.Column('display', sa.String(length=128), nullable=True, comment='Display name for status'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nomenclature_type',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for nomenclature type'),
    sa.Column('type', sa.String(length=255), nullable=False, comment='Nomenclature type'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species',
    sa.Column('taxon_id', sa.Integer(), nullable=False, comment='NCBI taxonomy identifier - primary key'),
    sa.Column('genefam_prefix', sa.String(length=11), nullable=False, comment='VGNC gene family prefix for this species'),
    sa.Column('primary_db_table', sa.String(length=255), nullable=True, comment='Primary database table name'),
    sa.Column('display_name', sa.String(length=128), nullable=False, comment='Display name for the species'),
    sa.Column('ensembl_species_name', sa.String(length=128), nullable=True, comment='Ensembl species name'),
    sa.Column('is_live', sa.Enum('Y', 'N', 'C', 'T', 'F', name='specieslivestatus'), nullable=False, comment='Species live status (Y/N/C/T/F)'),
    sa.Column('created', sa.DateTime(), nullable=False, comment='Creation timestamp'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('taxon_id'),
    comment='Species table - contains species information for VGNC project'
    )
    op.create_table('alt_name',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for alternative name'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Alternative name'),
    sa.Column('nomenclature_type_id', sa.Integer(), nullable=False, comment='Foreign key to nomenclature type'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['nomenclature_type_id'], ['nomenclature_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alt_symbol',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for alternative symbol'),
    sa.Column('symbol', sa.String(length=45), nullable=False, comment='Alternative symbol'),
    sa.Column('nomenclature_type_id', sa.Integer(), nullable=False, comment='Foreign key to nomenclature type'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['nomenclature_type_id'], ['nomenclature_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assembly',
    sa.Column('id', sa.Integer(), nullable=False, comment='Auto-increment primary key for assembly'),
    sa.Column('taxon_id', sa.Integer(), nullable=False, comment='Foreign key reference to species table'),
    sa.Column('source', sa.String(length=128), nullable=False, comment='Assembly source (e.g., Ensembl, NCBI)'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Assembly name'),
    sa.Column('genbank_assembly_accession', sa.String(length=128), nullable=False, comment='GenBank assembly accession'),
    sa.Column('refseq_assembly_accession', sa.String(length=128), nullable=False, comment='RefSeq assembly accession'),
    sa.Column('is_current', sa.Boolean(), nullable=False, comment='Whether this is the current assembly'),
    sa.Column('is_vgnc_default', sa.Boolean(), nullable=False, comment='Whether this is the VGNC default assembly'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['taxon_id'], ['species.taxon_id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Assembly table - contains genome assembly information'
    )
    op.create_table('chromosomes',
    sa.Column('chr_id', sa.Integer(), nullable=False, comment='Auto-increment primary key for chromosome'),
    sa.Column('taxon_id', sa.Integer(), nullable=False, comment='Foreign key reference to species table'),
    sa.Column('display_name', sa.String(length=128), nullable=False, comment='Display name for the chromosome'),
    sa.Column('coord_system', sa.String(length=128), nullable=True, comment='Coordinate system'),
    sa.Column('refseq_accession', sa.String(length=128), nullable=True, comment='RefSeq accession number'),
    sa.Column('genbank_accession', sa.String(length=128), nullable=False, comment='GenBank accession number'),
    sa.Column('ensembl_accession', sa.String(length=128), nullable=True, comment='Ensembl accession number'),
    sa.Column('type', sa.String(length=128), nullable=True, comment='Chromosome type'),
    sa.Column('assigned_to', sa.Integer(), nullable=True, comment='Assignment information'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['taxon_id'], ['species.taxon_id'], ),
    sa.PrimaryKeyConstraint('chr_id'),
    comment='Chromosomes table - contains chromosome information for VGNC project'
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for comment'),
    sa.Column('comment', sa.Text(), nullable=False, comment='Comment text'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='Author who created the comment'),
    sa.Column('locked', sa.Integer(), nullable=True, comment='Lock status'),
    sa.Column('created', sa.DateTime(), nullable=False, comment='Creation date'),
    sa.Column('publisher_id', sa.Integer(), nullable=True, comment='Publisher ID'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Comment status'),
    sa.Column('status_date', sa.DateTime(), nullable=False, comment='Status date'),
    sa.Column('replace_id', sa.Integer(), nullable=True, comment='Replace ID'),
    sa.Column('replacement_id', sa.Integer(), nullable=True, comment='Replacement ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['author_id'], ['editor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_new',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for family'),
    sa.Column('abbreviation', sa.String(length=255), nullable=True, comment='Family abbreviation'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Family name'),
    sa.Column('curator_comment', sa.Text(), nullable=True, comment='Curator comment'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='Family status'),
    sa.Column('external_note', sa.Text(), nullable=True, comment='External note'),
    sa.Column('type', sa.String(length=50), nullable=True, comment='Family type'),
    sa.Column('desc_comment', sa.Text(), nullable=True, comment='Description comment'),
    sa.Column('desc_label', sa.String(length=255), nullable=True, comment='Description label'),
    sa.Column('desc_source', sa.String(length=255), nullable=True, comment='Description source'),
    sa.Column('desc_go', sa.String(length=255), nullable=True, comment='Description GO annotation'),
    sa.Column('typical_gene', sa.String(length=50), nullable=True, comment='Typical gene for this family'),
    sa.Column('editor_id', sa.Integer(), nullable=False, comment='Editor who created this family'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['editor_id'], ['editor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gene_flag',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for gene flag'),
    sa.Column('type', sa.String(length=255), nullable=False, comment='Flag type'),
    sa.Column('flag_class_id', sa.Integer(), nullable=False, comment='Foreign key to flag class'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['flag_class_id'], ['flag_class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genefam',
    sa.Column('genefam_id', sa.Integer(), nullable=False, comment='Auto-increment primary key for gene family entries'),
    sa.Column('taxon_id', sa.Integer(), nullable=False, comment='Foreign key reference to species table'),
    sa.Column('assigned_id', sa.String(length=255), nullable=False, comment='Assigned gene family identifier'),
    sa.Column('assigned_symbol', sa.String(length=45), nullable=True, comment='Assigned gene symbol'),
    sa.Column('assigned_name', sa.String(length=255), nullable=True, comment='Assigned gene name'),
    sa.Column('status_id', sa.Integer(), nullable=False, comment='Foreign key reference to gene status'),
    sa.Column('editor_id', sa.Integer(), nullable=False, comment='Foreign key reference to editor who assigned this'),
    sa.Column('hcop_support_level', sa.Integer(), nullable=True, comment='HCOP support level rating'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['editor_id'], ['editor.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['gene_status.id'], ),
    sa.ForeignKeyConstraint(['taxon_id'], ['species.taxon_id'], ),
    sa.PrimaryKeyConstraint('genefam_id'),
    comment='Genefam table - contains gene family information for VGNC project'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genefam')
    op.drop_table('gene_flag')
    op.drop_table('family_new')
    op.drop_table('comment')
    op.drop_table('chromosomes')
    op.drop_table('assembly')
    op.drop_table('alt_symbol')
    op.drop_table('alt_name')
    op.drop_table('species')
    op.drop_table('nomenclature_type')
    op.drop_table('gene_status')
    op.drop_index('idx_gene_has_flag_genefam', table_name='gene_has_flag')
    op.drop_index('idx_gene_has_flag_flag', table_name='gene_has_flag')
    op.drop_table('gene_has_flag')
    op.drop_index('idx_gene_has_family_genefam', table_name='gene_has_family')
    op.drop_index('idx_gene_has_family_family', table_name='gene_has_family')
    op.drop_table('gene_has_family')
    op.drop_index('idx_gene_has_comment_genefam', table_name='gene_has_comment')
    op.drop_index('idx_gene_has_comment_comment', table_name='gene_has_comment')
    op.drop_table('gene_has_comment')
    op.drop_index('idx_gene_alt_symbol_symbol_id', table_name='gene_alt_symbol')
    op.drop_index('idx_gene_alt_symbol_genefam', table_name='gene_alt_symbol')
    op.drop_table('gene_alt_symbol')
    op.drop_index('idx_gene_alt_name_name_id', table_name='gene_alt_name')
    op.drop_index('idx_gene_alt_name_genefam', table_name='gene_alt_name')
    op.drop_table('gene_alt_name')
    op.drop_table('flag_class')
    op.drop_table('editor')
    op.drop_index('idx_assembly_has_chr_chr', table_name='assembly_has_chr')
    op.drop_index('idx_assembly_has_chr_assembly', table_name='assembly_has_chr')
    op.drop_table('assembly_has_chr')
    # ### end Alembic commands ###
