"""add_scientific_common_name_columns

Revision ID: 39a962ee2c82
Revises: 2299f7d46a8d
Create Date: 2025-11-11 16:48:21.781589

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '39a962ee2c82'
down_revision: str | Sequence[str] | None = '2299f7d46a8d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add missing scientific and common name columns to species table
    op.add_column('species', sa.Column('_scientific_name', sa.String(length=128), nullable=True, comment='Override for scientific name (optional)'))
    op.add_column('species', sa.Column('_common_name', sa.String(length=128), nullable=True, comment='Override for common name (optional)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove scientific and common name columns from species table
    op.drop_column('species', '_common_name')
    op.drop_column('species', '_scientific_name')
    # ### end Alembic commands ###
